### ISSUE TITLE
Database Storage of URLs

### ISSUE THREAD

**Issue by heynemann** [yourselfhosted/slash#49]
### Is your feature request related to a problem?

I really want to use this at my company for everyone to use together, but we need to store the links in a database such that we can run this in Kubernetes and not depend on the filesystem. Any chance this has come up already? If it is something you would consider adding as a feature I'd be happy to contribute.

### Describe the solution you'd like

Provide the capability to abstract url storage and retrieval to allow filesystem and other storage options such as relational or document databases.

**Comment by boojack** [comment]
Hi @heynemann, we also have plans to support other databases instead of SQLite. And I'm a bit curious as to which you're more comfortable with, MySQL or PostgreSQL?

**Comment by heynemann** [comment]
Either would be fine. What do you think of supporting Gorm and then we can easily allow for a myriad of dbs. We can definitely start with either pg or MySQL.

**Comment by boojack** [comment]
How about just raw SQL? Just like the way it is now for SQLite. Personally, I think that Go's ORM is kind of not good and writing raw SQL is more clearer and easier to understand.

A related discussion: https://github.com/usememos/memos/issues/2517#issuecomment-1826790893

**Comment by heynemann** [comment]
Can surely do that :) In  such a small problem space TBH whatever works best for slash. Will try to send something your way soon.

**Comment by boojack** [comment]
FYI, we just implemented postgres driver. If you want, you can start with the `yourselfhosted/slash:test` docker image. All you need to do is add the related flags in startup command. e.g.,

```bash
docker run -d --name slash -p 5231:5231 -v ~/.slash/:/var/opt/slash yourselfhosted/slash:test --driver postgres --dsn 'postgresql://postgres:PASSWORD@localhost:5432/memos'
```

**Comment by heynemann** [comment]
With this docker-compose I'm getting an error migrating the DB. There seems to be an opportunity here to improve the logging of errors in migrating as it seems to be swallowing errors.

```
version: '3'
services:
  postgres:
    image: postgres
    restart: always
    user: root
    ports:
      - "5432:5432"
    environment:
      PGUSER: slash
      POSTGRES_USER: slash
      POSTGRES_PASSWORD: slash
      POSTGRES_DATABASE: slash
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - local

  slash:
    image: yourselfhosted/slash:test
    container_name: slash
    ports:
      - "5231:5231"
    volumes:
      - ~/.slash/:/var/opt/slash
    command: --driver postgres --dsn 'postgresql://slash:slash@postgres:5432/slash'
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - local

networks:
  local:
```
